Task1 shamonin
Phil-Shepard/Telegram_Bot_Auto_Parts_Store pull request #2
Opened 2023-11-20 12:25 UTC by Phil-Shepard

Объединил Илюхин и свой код

2023-11-20 13:02 UTC, lomonoga requested changes

2023-11-20 13:02 UTC, lomonoga commented on src/main/java/com/urfu/bot/services/car/CarServiceImpl.java
> +        }
Лучше использовать специальны метод foreach

2023-11-20 13:02 UTC, lomonoga commented on src/main/java/com/urfu/bot/storage/Storage.java
> +        }
Тоже самое

2023-11-20 13:02 UTC, lomonoga commented on .idea/encodings.xml
.idea исключить

2023-11-20 13:02 UTC, lomonoga commented on .idea/misc.xml
.idea исключить

2023-11-20 13:02 UTC, lomonoga commented on .idea/vcs.xml
.idea исключить

2023-11-20 13:02 UTC, lomonoga commented on .idea/workspace.xml
.idea исключить

2023-11-20 13:02 UTC, lomonoga commented on src/main/java/com/urfu/bot/telegram/Logic.java
> +    }
Здесь не должно быть логики работы. Только лишь вызов команды с Handler

2023-11-20 13:02 UTC, lomonoga commented on src/main/java/com/urfu/bot/commands/Commands.java
> +}
Почему пустой?

2023-11-20 13:02 UTC, lomonoga commented on src/main/java/telegram/Main.java
> +//        }
Удалить бесполезные комментарии

2023-11-20 13:02 UTC, lomonoga commented on src/main/java/telegram/bot/Logic.java
> +    private Lada lada = new Lada("Lada", "колёса ","двигатель ","зеркала ","фары ","дворники");
В логике заполнение данных не должно присутствовать

2023-11-20 13:02 UTC, lomonoga commented on src/main/java/telegram/bot/TelegramBot.java
> +}
Повторение кода? Удалить все повторяющие файлы

2023-11-20 13:02 UTC, lomonoga commented on src/main/java/telegram/cars/Car.java
> +    }
Одна и та же логика. Значит можно вынести. Но лучше даже не выносить, а просто тернарником. Но можно и по другому логику выстроить

2023-11-20 13:23 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/telegram/Logic.java
> +    }
Это я вынесу в команды

2023-11-20 13:23 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/commands/Commands.java
> +}
Заполню

2023-11-20 13:23 UTC, Phil-Shepard commented on src/main/java/telegram/Main.java
> +//        }
Ок

2023-11-21 11:36 UTC, lomonoga commented on src/main/java/com/urfu/bot/services/car/CarServiceImpl.java
> +        }
Не исправил

2023-11-21 11:36 UTC, lomonoga commented on src/main/java/com/urfu/bot/storage/Storage.java
> +        }
То же самое

2023-11-21 11:37 UTC, lomonoga commented on src/main/java/com/urfu/bot/commands/Commands.java
> +}
Надо сейчас, логика не должна выстраиваться потом

2023-11-21 20:15 UTC, closed without merging