Первая задача
Phil-Shepard/Telegram_Bot_Auto_Parts_Store pull request #5
Opened 2023-12-10 11:56 UTC by Phil-Shepard

2023-12-11 09:15 UTC, vpyzhyanov commented
Учитесь использовать gitignore

![image](https://github.com/Phil-Shepard/Telegram_Bot_Auto_Parts_Store/assets/71599019/6d8d1308-bffc-40de-8bac-8a79cad2b59b)

2023-12-11 09:16 UTC, vpyzhyanov commented
![image](https://github.com/Phil-Shepard/Telegram_Bot_Auto_Parts_Store/assets/71599019/820f50ea-f065-4f5b-a345-8eaec699586a)

Такие комментарии должны сопровождаться merge'ем. А не быть простыми коммитами

2023-12-11 09:19 UTC, vpyzhyanov commented
А ещё ключ в открытом доступе

![image](https://github.com/Phil-Shepard/Telegram_Bot_Auto_Parts_Store/assets/71599019/8a7c8809-f258-4c60-afd3-945872b855ec)

Благодаря всем этим замечаниями вы получаете 0 баллов за Git.

2023-12-13 17:34 UTC, vpyzhyanov requested changes
Очень плохо. Ребята, у вас 0 баллов за все пункты. Нарушили всё, что только можно было нарушить.

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/telegram/Constants.java
> +    public static List<BotCommand> listOfCommands() {
static запрещён!

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/telegram/TelegramBot.java
> +            System.out.println(e);
вы точно хотите продолжить работу приложения, если бот не запустился?

Тут нужно выбросить исключение с человекочитаемым текстом

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/telegram/Bot.java
> + * Интерфейс бота, для выполнения некоторых команд
1. Всем и так видно, что это интерфейс. Не нужно лишних слов
2. Что означает это таинственное описание? Во первых оно недостоверное (судя по методам интрерфейса), во вторых тайну наводит слово "некоторых". Никаких тайн в коде!!!

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/telegram/Bot.java
> +    void sendMessage(SendMessage message);
нет описания

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/telegram/BotConfig.java
> +    private final String botToken = "6661500007:AAFEMtc9b4GSHMvynNhimKRopwNPdsQaQ2U";
токен в открытом доступе. Не забудьте, пожалуйста сюда добавить номер вашей банковской карточки и 3 цифры на обороте)))

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/telegram/Constants.java
> +    public static final String command_start = "/start";
имя не соответствует общепринятому стилю. `COMMAND_START`. Всех остальных констант тоже касается

![image](https://github.com/Phil-Shepard/Telegram_Bot_Auto_Parts_Store/assets/71599019/58a90d2b-53fb-4b70-9115-a75a006e1304)

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/telegram/Logic.java
> +    public void onUpdateReceived(Update update) {
ох и зря вы завязались на телеграмм, выстрелили себе в ногу. Могли заметить это по сложностям, которые приходится делать при написании тестов. Убирайте любую связь с телеграммом. В импортах этого класса не должно быть ни одного упоминания телеграмма. Логика бота не должна быть никак связана с телеграммом

Можете тут явно передавать нужные параметры, можете создать свой класс

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/telegram/Logic.java
> +            CarServiceImpl carService = new CarServiceImpl();
1. И зачем вы создавали интерфейс, если вы им вообще не пользуетесь?
2. Зачем на **каждое** сообщение создавать новый экземпляр? Пожалейте память и сборщик мусора!

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/telegram/Logic.java
> +            message.setChatId(String.valueOf(chatId));
всей этой телеграммовской мишуры в **логике бота** быть не должно

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/telegram/Logic.java
> +                    commands.startCommandReceived(message, update.getMessage().getChat().getFirstName());
Очень странный и непонятный метод. Написано `Выводит приветствие и список возможных команд.`, но совершенно непонятно куда выводит.

Оказалось этот метод изменяет переданный параметр. Вы вообще меня на лекции не слушаете что ли? (тема "Стиль кодирования")

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/commands/Commands.java
> +        message.setReplyMarkup(getKeyBoard(getNameCars()));
Вопиющее нарушение всех норм и правил, которые я рассказывал на лекциях

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/commands/Commands.java
> +    public void GetShop(SendMessage message, CarServiceImpl carService){
имена методов, переменных, аргументов - должны быть с маленькой буквы

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/commands/Commands.java
> +     * @param car
Кому нужны все эти пустышки? Если вам нечего написать, то ничего не пишите

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/commands/Commands.java
> +            nameCars += car.getName()+ " ";
вы не видите предупреждение, которое подсвечивает IDEA?

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/commands/Commands.java
> +        ) {
пользуйтесь форматтированием. Скобку не принято переносить на следующую строку

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/commands/Commands.java
> +        return parts;
нет смысла тут выделять переменную

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/services/car/CarService.java
> +    List<Car> getCars();
Это метод используется только в реализации этого сервиса. Тогда зачем его выделять в интерфейс? Он не нужен

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/services/car/CarService.java
> +public interface CarService {
Задачи, без JavaDoc приниматься не будут!

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/services/car/CarServiceImpl.java
> +public class CarServiceImpl implements CarService{
Опять нет JavaDoc

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/services/car/CarServiceImpl.java
> +        return new Storage().getStorage();
О_о снова на каждый вызов новый экземпляр? Хорошо вы устроились, похоже у вас террабайты оперативной памяти, раз о ней вы совсем не думаете

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/domain/basket/Basket.java
> +public abstract class Basket {
класс нигде не используется и должен быть удалён

Странно, что корзина - абстрактный класс

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/domain/car/Bmw.java
> +public class Bmw extends Car{
1. Нет JavaDoc 
2. Вы перепутали наследование с экземплярами класса (см. самую первую лекцию по ООП). Это легко понять если спросить "чем ваш Bmw принципиально отличается от Lada? А ничем

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/domain/car/Car.java
> +    protected String name;
грубое нарушение инкапсуляции

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/domain/car/Car.java
> +    protected Wipers wipers;
Прошу меня простить, но я не могу, это кошмар какой-то. Такого я ещё не видел. Вся модель очень далека от реальности, удобства, расширяемости. Попробую объяснить что конкретно не так:

1. Все части машины жёстко зашиты в очень ограниченное число полей, чтобы добавить новую деталь нужно переписывать кучу кода.
2. Каждый класс отличается друг от друга только названием (перепутали наследование с созданием экземпляра класса)
3. Тотальное отсутствие JavaDoc в **каждом** классе

Правильно было делать **одно** поле `List<SpareParts>`

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/domain/car/Car.java
> +        return wipers.getAvailability();
абсолютно одинаковый код встречается 3 раза

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/domain/spareParts/SpareParts.java
> +public interface SpareParts {
Где JavaDoc?

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/domain/spareParts/SpareParts.java
> +     * Возвращает наличие запачсти
странно, что "наличие" это строка. Наличие - это true/false

А самое смешное то, что оказалось что "наличие" - это `"дворники"` и т.п. То есть названия объектов, а не наличие. В общем это наглая ложь!

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/domain/spareParts/wipers/Wipers.java
> +    private String availability;
1. во всех классах абсолютно одинаковое поле и одинаковый код
2. Неуместное использование наследование
3. Отсутствие JavaDoc

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/services/basket/BasketService.java
> +public interface BasketService {
класс не используется

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/services/spareParts/SparePartsService.java
> +public interface SparePartsService {
никому не нужный пустой интерфейс. На мусорку его!

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/storage/Storage.java
> +    private Lada lada = new Lada("Lada", new Wheels("колёса"), new Headlights("фары"), new Wipers("дворники"));
Какая необходимость их в поля сохранять?

2023-12-13 17:34 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/storage/Storage.java
> +        listCars.add(lada);
О_о не верю глазам своим. Зачем это всё делаете? А нельзя просто вернуть список машин, не пересоздавать его **каждый раз**?

2023-12-13 17:34 UTC, vpyzhyanov commented on src/test/java/com/urfu/bot/telegram/TestLogic.java
> +        Message messageMock = Mockito.mock(Message.class);
не нужно мокать обычные классы

Вам mickito тут вообще не нужен. Его использование неуместно! Прошу убрать его

2023-12-13 17:34 UTC, vpyzhyanov commented on src/test/java/com/urfu/bot/telegram/TestLogic.java
> +        Assert.assertEquals("В наличии комплектующиие для автомобилей: \n" + " BMW, Renault, Lada", fakeBot.getLastMessage());
А остальные команды проверять не надо?

2023-12-13 17:34 UTC, vpyzhyanov commented on src/test/java/com/urfu/bot/telegram/TestLogic.java
> +package com.urfu.bot.telegram;
класс логики к телеграмму не должна иметь никакого отношения

2023-12-13 17:34 UTC, vpyzhyanov commented on src/test/java/com/urfu/bot/telegram/TestLogic.java
> +        Assert.assertEquals("В наличии комплектующиие для автомобилей: \n" + " BMW, Renault, Lada", fakeBot.getLastMessage());
даже в тесте зафиксирована **опечатка**

2023-12-13 17:42 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/telegram/BotConfig.java
> +    private final String botToken = "6661500007:AAFEMtc9b4GSHMvynNhimKRopwNPdsQaQ2U";
А это точно безопасно?)

2023-12-14 16:09 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/telegram/Constants.java
> +    public static List<BotCommand> listOfCommands() {
Исправлено!

2023-12-14 16:09 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/telegram/TelegramBot.java
> +            System.out.println(e);
Написал хорошее исключение

2023-12-14 16:10 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/telegram/Bot.java
> + * Интерфейс бота, для выполнения некоторых команд
Исправил описание

2023-12-14 16:10 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/telegram/Bot.java
> +    void sendMessage(SendMessage message);
Добавил описание

2023-12-14 16:11 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/telegram/Constants.java
> +    public static final String command_start = "/start";
Исправлены все константы по общепринятому стилю

2023-12-14 16:11 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/telegram/Logic.java
> +    public void onUpdateReceived(Update update) {
Не совсем понял, что вы имели в виду, но будем пробовать исправить

2023-12-14 16:12 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/telegram/Logic.java
> +    public void onUpdateReceived(Update update) {
Понял всё, кроме последнего предложения, исправим

2023-12-14 16:13 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/telegram/Logic.java
> +            CarServiceImpl carService = new CarServiceImpl();
Вынес экземпляр за метод, чтобы экономить память

2023-12-14 16:13 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/telegram/Logic.java
> +            message.setChatId(String.valueOf(chatId));
Хорошо

2023-12-14 16:13 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/telegram/Logic.java
> +                    commands.startCommandReceived(message, update.getMessage().getChat().getFirstName());
Исправил описание метода

2023-12-14 16:14 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/commands/Commands.java
> +        message.setReplyMarkup(getKeyBoard(getNameCars()));
Не совсем понял, что вы имели в виду, но стилистически исправил код переносом строки.

2023-12-14 16:14 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/commands/Commands.java
> +    public void GetShop(SendMessage message, CarServiceImpl carService){
Исправлено!

2023-12-14 16:14 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/commands/Commands.java
> +     * @param car
Исправлено

2023-12-14 16:15 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/commands/Commands.java
> +            nameCars += car.getName()+ " ";
Вижу, исправлено
Сделал стрингбилдер

2023-12-14 16:16 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/commands/Commands.java
> +        ) {
Исправлено

2023-12-14 16:16 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/commands/Commands.java
> +        return parts;
Исправлено

2023-12-14 16:18 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/services/car/CarService.java
> +    List<Car> getCars();
Прислушался к вашим замечаниям, действительно интерфейс не нужен, удалён

2023-12-14 16:18 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/services/car/CarService.java
> +public interface CarService {
Данный интерфейс удалён по вашей рекомендации выше

2023-12-14 16:21 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/services/car/CarServiceImpl.java
> +public class CarServiceImpl implements CarService{
Написал все джава доки

2023-12-14 16:27 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/services/car/CarServiceImpl.java
> +        return new Storage().getStorage();
Исправил, вынес создание экземпляра класса за метод, чтобы лишь единожды тратилась память на инициализацию.

2023-12-14 16:28 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/domain/basket/Basket.java
> +public abstract class Basket {
Удалено!

2023-12-14 16:37 UTC, Estoneccc commented on src/main/java/com/urfu/bot/storage/Storage.java
> +    public void AddStorage(){
.

2023-12-14 16:44 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/domain/car/Bmw.java
> +public class Bmw extends Car{
Добавлен JavaDOC, в целом классы ничем не отличаются, вы правы

2023-12-14 16:46 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/domain/car/Car.java
> +    protected String name;
Данная груба ошибка исправлена, модификатор доступа изменён на private

2023-12-14 16:55 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/domain/car/Car.java
> +    protected Wipers wipers;
1. Согласен с вами, есть такой курьёз
2. Переделал, удалил классы машин, просто сделал создание экземпляров класса, вместо ужасного "наследования", каким оно по факту не являлось
3. JavaDOCи написаны

2023-12-14 17:13 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/domain/car/Car.java
> +        return wipers.getAvailability();
Исправил, создал универсальный метод, который возвращает любую запчасть.

2023-12-14 17:44 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/domain/spareParts/SpareParts.java
> +public interface SpareParts {
Написал

2023-12-14 17:47 UTC, Estoneccc commented on src/test/java/com/urfu/bot/telegram/TestLogic.java
> +        Message messageMock = Mockito.mock(Message.class);
Понял, убрал моки, заменил их на обычные классы Update, Message и Chat

2023-12-14 17:51 UTC, Estoneccc commented on src/test/java/com/urfu/bot/telegram/TestLogic.java
> +        Assert.assertEquals("В наличии комплектующиие для автомобилей: \n" + " BMW, Renault, Lada", fakeBot.getLastMessage());
это просто тесты только для команд из первого задания

2023-12-14 17:52 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/domain/spareParts/SpareParts.java
> +     * Возвращает наличие запачсти
Согласен с вами, это логическая ошибка. Я её исправил, теперь метод называется getName( ), и переменная называется не "наличие", а "имя" запчасти

2023-12-14 18:03 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/services/basket/BasketService.java
> +public interface BasketService {
Удалил

2023-12-14 18:04 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/domain/spareParts/wipers/Wipers.java
> +    private String availability;
Исправил: удалил ненужные классы. Сделал инициализацию объектов класса, вместо "наследования"
Прописал JavaDOC

2023-12-14 18:17 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/services/spareParts/SparePartsService.java
> +public interface SparePartsService {
Вместо интерфейса сделал класс, который используется вместо трёх ненужный классов.

2023-12-14 18:18 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/storage/Storage.java
> +        listCars.add(lada);
Переделал, возвращаю список машин, не создавая его.

2023-12-14 18:36 UTC, Estoneccc commented on src/test/java/com/urfu/bot/telegram/TestLogic.java
> +        Assert.assertEquals("В наличии комплектующиие для автомобилей: \n" + " BMW, Renault, Lada", fakeBot.getLastMessage());
Поправил

2023-12-14 18:59 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/storage/Storage.java
> +    private Lada lada = new Lada("Lada", new Wheels("колёса"), new Headlights("фары"), new Wipers("дворники"));
Мне так показалось удобнее

2023-12-20 17:26 UTC, Estoneccc commented on src/test/java/com/urfu/bot/telegram/TestLogic.java
> +package com.urfu.bot.telegram;
Поправили

2023-12-20 17:36 UTC, vpyzhyanov commented
Похоже вы не хотите получать баллы за гит. Всё ещё **не используете ветки**, всё ещё **не используете пулл реквесты**.

![image](https://github.com/Phil-Shepard/Telegram_Bot_Auto_Parts_Store/assets/71599019/38c40a9f-912a-4cc8-b50c-c7fe02135ab4)

Делать Force push при открытом пулл реквесте - делать нельзя! Так вы затираете историю изменений, это плохо как для вас, так и для ревьюера, но для ревьюера это ещё больнее.

![image](https://github.com/Phil-Shepard/Telegram_Bot_Auto_Parts_Store/assets/71599019/5fedaf37-a926-4982-8f80-306d87e40906)
 
Тем не менее 1 балл всё же поставлю, т.к. вы убрали мусор из репозитория и убрали токен.

2023-12-20 17:52 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/telegram/TelegramBot.java
> +            System.out.println(e);
чем же оно хорошее? 

1. `TelegramApiException` принадлежит API, вы не вправе его использовать. Точнее это введёт в заблуждение.
2. Просто взяли **это же** исключение, **выкинули из него стек**, который может содержать очень полезную информацию, оставив только сообщение и бросили дальше. В чём смысл? Могли просто ничего не перехватывать.
3. Я писал, что тут должен быть **человекочитаемый** текст ошибки, но вы это проигнорировали

В общем, надо сделать следующее

```java
         catch (TelegramApiException e){
            throw new RuntimeException("Не удалось создать кнопки. " 
                                       + e.getMessage(), e);
        }
```

1. Создать новое исключение с читаемым текстом, указав последним параметром исходное исключение, чтобы прокинуть стек
2. Убрать `throws TelegramApiException`

2023-12-20 18:48 UTC, vpyzhyanov requested changes
Протестирована не вся функциональность даже после сделанного замечания. Это даёт -1 балл к задаче.

Всё ещё присутствуют многочисленные нарушения инкапсуляции.

Несмотря на замечания вы всё ещё изменяете переданные параметры, хоть это делать вообще не нужно, да и не удобно. Финт с клонированием проблему не решил, да и мы не принимаем "лазейки" (типа ссылку поменяли, значит параметр уже не меняем), а принимаем только полноценные решения. Тем более решить проблему очень просто.

Итого за ООП: **3 балла** (хотя это много)

В общем задачу я принял, иначе вы не успеете сдать все задачи, как исправите последние замечания, можете мёрджить. Если не исправите, то за вторую задачу получите сразу 0.

2023-12-20 18:48 UTC, vpyzhyanov commented on src/main/java/com/urfu/domain/message/MessageToUser.java
> +    public MessageToUser clone() {
Зачем вам вообще клонирование? Если вы хотите установить сообщение или изменить кнопки, то это можно сделать сеттерами. А так вы только процессорное время и память впустую тратите.

2023-12-20 18:48 UTC, vpyzhyanov commented on src/main/java/com/urfu/domain/message/MessageToUser.java
> +            throw new AssertionError();
1. нет сообщения, никакого
2. "Левое" исключение, которое вообще ни о чём не говорит

2023-12-20 18:48 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/telegram/BotConfig.java
> +    private final String botToken = "6661500007:AAFEMtc9b4GSHMvynNhimKRopwNPdsQaQ2U";
точно)

2023-12-20 18:48 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/BotLogic.java
> +            MessageToUser message = new MessageToUser();
Зачем его создавать здесь? Разве этот метод формирует ответ пользователю? Нет, не формирует. Он делегирует эту задачу `botCommands`.

Уберите это от сюда. Создавайте класс только там, где вы его будут наполнять полезными данными.

2023-12-20 18:48 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/BotLogic.java
> +            message.setChatId(chatId);
нельзя было просто в качестве аргумента передать chatId? Можно ведь! И не надо делать все эти трюки с **клонированием**, т.е. не надо использовать совершенно неподходящий для этого инструмент.

2023-12-20 18:48 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/commands/Commands.java
> +        message.setReplyMarkup(getKeyBoard(getNameCars()));
Я имел в виду, что изменять переданные параметры нельзя. Но и с вашим клонированием тоже получилось не лучше. По сути кроме новой ссылки ничего не изменилось. Точно так же изменяете переданный аргумент, только создали его копию. Надо было конструктор использовать и заполнять честно все параметры. И аргументы передавать нормально, а не заворачивать их в объект, который и хотите вернуть.

2023-12-20 18:48 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/BotCommands.java
> +public class BotCommands {
наглая ложь! Ни одной команды в этом классе нет!

2023-12-20 18:48 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/BotCommands.java
> +    public MessageToUser setNamesButtonsAndSetTextNamesOfShop(MessageToUser messageToUser, CarService carService){
у этого класса нет ни одного поля, чтобы вызывать сеттер. Впрочем как только вы перестанете пытаться менять переданные параметры, всё встанет на свои места, имена методов в том числе

2023-12-20 18:48 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/BotCommands.java
> +        resultMessageToUser.setText("Вы закрыли каталог товаров");
что-то не похоже на "Удаление кнопок бота"

2023-12-20 18:48 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/services/car/CarService.java
> +    List<Car> getCars();
Вы неправильно меня поняли. Замечание касается только метода `getCars()`, а не всего интерфейса. Вы добавили в интерфейс метод, который используете только внутри реализации. То есть его можно сделать private и определить только **внутри реализации**

2023-12-20 18:48 UTC, vpyzhyanov commented on src/main/java/com/urfu/services/CarService.java
> +    public List<Car> getCars() {
нарушение инкапсуляции. Метод который используется только внутри класса должен быть приватным.

2023-12-20 18:48 UTC, vpyzhyanov commented on src/main/java/com/urfu/services/CarService.java
> +    Storage storage = new Storage();
нарушение инкапсуляции. Изменяйте storage кто хочет, пожалуйста, можно всё творить с ним внутри этого пакета!))

2023-12-20 18:48 UTC, vpyzhyanov commented on src/main/java/com/urfu/storage/Storage.java
> +    public List<Car> getStorage() {
название и описание не соответствует друг другу. Имя "вернуть хранилище", а описание про машины говорит. Как понять кто прав?

2023-12-20 18:48 UTC, vpyzhyanov commented on src/main/java/com/urfu/bot/services/spareParts/SparePartsService.java
> +public interface SparePartsService {
Зачем? В этом методе только один метод, который состоит из **одной** строчки. В нём нет никакого смысла

2023-12-20 18:48 UTC, vpyzhyanov commented on src/main/java/com/urfu/services/SparePartService.java
> +        return car.getAvailabilityParts();
однострочный метод не имеет смысла и должен быть удалён. Как и весь этот класс. Логики в нём нет никакой, только геттер у переданного параметра вызывает, он бесполезен.

2023-12-20 18:48 UTC, vpyzhyanov commented on src/test/java/com/urfu/bot/telegram/TestLogic.java
> +        Assert.assertEquals("В наличии комплектующиие для автомобилей: \n" + " BMW, Renault, Lada", fakeBot.getLastMessage());
Ну и что? Это не значит, что не нужно проверять все команды **первого** задания. Вывод запчастей конкретной машины не проверяется, да и вообще вывод запчастей не проверяется.

2023-12-20 18:48 UTC, vpyzhyanov commented on src/test/java/com/urfu/bot/TestBotLogic.java
> +                Справка о дуступных командах:
даже в тесте зафиксирована опечатка

2023-12-21 08:34 UTC, Phil-Shepard commented on src/main/java/com/urfu/bot/telegram/TelegramBot.java
> +            System.out.println(e);
Исправлено!
Спасибо за подсказку

2023-12-21 08:35 UTC, Estoneccc commented on src/main/java/com/urfu/domain/message/MessageToUser.java
> +    public MessageToUser clone() {
Клонирование убрали

2023-12-21 08:35 UTC, Estoneccc commented on src/main/java/com/urfu/domain/message/MessageToUser.java
> +            throw new AssertionError();
Клонирование убрали

2023-12-21 08:38 UTC, Estoneccc commented on src/main/java/com/urfu/bot/BotLogic.java
> +            MessageToUser message = new MessageToUser();
Теперь сообщение создается только в botCommands

2023-12-21 08:38 UTC, Estoneccc commented on src/main/java/com/urfu/bot/BotLogic.java
> +            message.setChatId(chatId);
Исправил

2023-12-21 09:19 UTC, Estoneccc commented on src/main/java/com/urfu/bot/BotCommands.java
> +public class BotCommands {
Согласен, класс по факту для создания сообщений для пользователя

2023-12-21 09:21 UTC, Estoneccc commented on src/main/java/com/urfu/bot/BotCommands.java
> +    public MessageToUser setNamesButtonsAndSetTextNamesOfShop(MessageToUser messageToUser, CarService carService){
Исправил

2023-12-21 09:21 UTC, Estoneccc commented on src/main/java/com/urfu/bot/BotCommands.java
> +        resultMessageToUser.setText("Вы закрыли каталог товаров");
Согласен, исправил

2023-12-21 09:43 UTC, Estoneccc commented on src/main/java/com/urfu/services/CarService.java
> +    public List<Car> getCars() {
Исправил

2023-12-21 09:44 UTC, Estoneccc commented on src/main/java/com/urfu/services/CarService.java
> +    Storage storage = new Storage();
Исправил)

2023-12-21 09:48 UTC, Estoneccc commented on src/main/java/com/urfu/storage/Storage.java
> +    public List<Car> getStorage() {
Поправил

2023-12-21 09:48 UTC, Estoneccc commented on src/main/java/com/urfu/services/SparePartService.java
> +        return car.getAvailabilityParts();
Класс удален

2023-12-21 09:49 UTC, Estoneccc commented on src/test/java/com/urfu/bot/TestBotLogic.java
> +                Справка о дуступных командах:
Недоразумение исправлено

2023-12-21 10:05 UTC, merged